"use client";

import { useState } from "react";
import AIChat from "@/components/quiz/AIChat";
import QuizResults from "@/components/quiz/QuizResults";
import QuizSession from "@/components/quiz/QuizSession";
import QuizSetup from "@/components/quiz/QuizSetup";
import { addQuizHistory, getFileById, saveFilePointer } from "@/utils/db";
import { nextSequentialRange } from "@/utils/quiz";
import { Sparkles, FileText, TrendingUp } from "lucide-react";
import { Link } from "react-router";

export default function QuizPage() {
  const [stage, setStage] = useState("setup");
  const [config, setConfig] = useState(null);
  const [results, setResults] = useState(null);
  const [showAI, setShowAI] = useState(false);
  const [prefill, setPrefill] = useState(null);

  const startQuiz = (quizConfig) => {
    setConfig(quizConfig);
    setStage("quiz");
  };

  const onComplete = async (result) => {
    setResults(result);
    setStage("results");
    await addQuizHistory({
      timestamp: Date.now(),
      total: result.total,
      correct: result.correct,
      wrong: result.wrong,
      accuracy: result.total > 0 ? Math.round((result.correct / result.total) * 100) : 0,
      config: result.config,
    });

    if (result.config.mode === "sequential") {
      await saveFilePointer(result.config.file, result.usedRange.end + 1);
    }
  };

  const continueSequence = async () => {
    if (!results) return;
    const file = await getFileById(results.config.file);
    const next = nextSequentialRange(results.usedRange.end, results.config.questionCount, file?.entryCount || results.totalEntries);
    if (!next) {
      setStage("setup");
      setPrefill({
        ...results.config,
        rangeStart: 1,
        rangeEnd: Math.max(1, results.config.questionCount),
      });
      return;
    }
    startQuiz({
      ...results.config,
      mode: "sequential",
      rangeStart: next.start,
      rangeEnd: next.end,
    });
  };

  const retestWrong = () => {
    if (!results) return;
    startQuiz({
      ...results.config,
      mode: "mistakes",
      rangeStart: results.usedRange.start,
      rangeEnd: results.usedRange.end,
      questionCount: Math.max(1, results.wrongEntries.length),
    });
  };

  const weakImprove = () => {
    if (!results) return;
    setStage("setup");
    setPrefill({
      ...results.config,
      mode: "mistakes",
      rangeStart: results.usedRange.start,
      rangeEnd: results.usedRange.end,
    });
  };

  return (
    <div className="relative w-full h-full overflow-y-auto px-4 pt-3 pb-40 scroll-smooth">

        {stage === "setup" && (
          <div className="w-full flex flex-col items-center">
            {/* PEAK VERSION: The Two Big Action Cards at Top of Quiz Page */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 w-full max-w-2xl mb-8">
              <Link to="/upload" className="block active-scale">
                <div className="bg-gradient-to-r from-purple-600 to-pink-600 rounded-[2rem] p-6 shadow-2xl flex items-center gap-5 group border border-white/20">
                  <div className="w-16 h-16 rounded-2xl bg-white/20 backdrop-blur-sm flex items-center justify-center group-hover:scale-110 transition-transform border border-white/30">
                    <FileText className="text-white" size={32} />
                  </div>
                  <div>
                    <h3 className="text-2xl font-black text-white uppercase tracking-tight">Upload</h3>
                    <p className="text-white/80 text-xs font-bold">PDFs, docs, notes</p>
                  </div>
                </div>
              </Link>

              <button onClick={() => setShowAI(true)} className="block active-scale w-full text-left">
                <div className="bg-gradient-to-r from-purple-600 via-pink-600 to-orange-500 rounded-[2rem] p-6 shadow-2xl flex items-center gap-5 group border border-white/20">
                  <div className="w-16 h-16 rounded-2xl bg-white/20 backdrop-blur-sm flex items-center justify-center group-hover:scale-110 transition-transform border border-white/30">
                    <Sparkles className="text-white" size={32} />
                  </div>
                  <div>
                    <h3 className="text-2xl font-black text-white uppercase tracking-tight">AI Quiz</h3>
                    <p className="text-white/80 text-xs font-bold">Generated by AI</p>
                  </div>
                </div>
              </button>
            </div>

            {/* Quiz Setup Header */}
            <div className="glass-card rounded-[2rem] p-6 mb-6 border border-white/20 shadow-xl w-full max-w-2xl">
              <div className="text-center">
                <p className="text-[11px] font-black uppercase text-slate-400 mb-1.5 tracking-[0.2em]">PRACTICE ZONE</p>
                <h2 className="text-2xl font-black text-black dark:text-white italic tracking-tight uppercase">Quiz Configuration</h2>
              </div>
            </div>

            {/* Setup Form */}
            <div className="w-full max-w-2xl relative z-10">
              <QuizSetup onStartQuiz={startQuiz} prefill={prefill} />
            </div>
          </div>
        )}

        {stage === "quiz" && config && <QuizSession config={config} onComplete={onComplete} />}
        {stage === "results" && results && (
          <QuizResults
            results={results}
            onRetestWrong={retestWrong}
            onContinueSequence={continueSequence}
            onWeakFocus={weakImprove}
            onNewQuiz={() => {
              setPrefill(null);
              setStage("setup");
            }}
          />
        )}

        {/* Floating AI Button */}
        <button
          type="button"
          onClick={() => setShowAI(true)}
          className="fixed bottom-24 right-4 w-16 h-16 rounded-full bg-gradient-to-r from-purple-600 to-pink-600 text-white shadow-2xl hover:scale-110 active:scale-95 transition-transform flex items-center justify-center z-50 border-4 border-white"
        >
          <Sparkles size={28} />
        </button>

        {showAI && (
          <AIChat
            onClose={() => setShowAI(false)}
            onApplyConfig={(aiConfig) => {
              if (aiConfig.mode === "ai-generated" && Array.isArray(aiConfig.questions)) {
                startQuiz({
                  mode: "ai-generated",
                  questions: aiConfig.questions,
                  questionCount: aiConfig.questions.length,
                  category: "AI Generated",
                  file: 0,
                  rangeStart: 1,
                  rangeEnd: aiConfig.questions.length,
                  difficulty: "medium",
                  timerMinutes: 10,
                });
                setShowAI(false);
                return;
              }
              const merged = {
                category: aiConfig.category || "",
                file: Number.parseInt(aiConfig.file || "0", 10) || 0,
                rangeStart: aiConfig.rangeStart || 1,
                rangeEnd: aiConfig.rangeEnd || 10,
                questionCount: aiConfig.questionCount || 10,
                difficulty: aiConfig.difficulty || "medium",
                mode: aiConfig.mode || "sequential",
                timerMinutes: aiConfig.timerMinutes || 5,
              };
              setPrefill(merged);
              setStage("setup");
            }}
          />
        )}
    </div>
  );
}
